version: "3"

services:

  runtime-setup:
    image: netty-io_uring:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos6

  common: &common
    image: netty-io_uring:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.m2/repository:/root/.m2/repository
      - ..:/code:delegated
    working_dir: /code

  build-leak:
    <<: *common
    command: /bin/bash -cl "./mvnw -B -ntp -Pleak clean test -Dio.netty.testsuite.badHost=netty.io"

  build: 
    <<: *common
    command: /bin/bash -cl "./mvnw -B -ntp clean package -Dio.netty.testsuite.badHost=netty.io"

  deploy:
    <<: *common
    command: /bin/bash -cl "./mvnw -B -ntp clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  stage-snapshot:
    <<: *common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "./mvnw -B -ntp clean javadoc:jar package org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true"

  stage-release:
    <<: *common
    environment:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_PRIVATE_KEY
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "cat <(echo -e \"${GPG_PRIVATE_KEY}\") | gpg --batch --import && ./mvnw -B -ntp clean javadoc:jar package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org -DserverId=sonatype-nexus-staging -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.keyname=${GPG_KEYNAME}"


  shell:
    <<: *common
    environment:
      - SONATYPE_USER
      - SONATYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash
