version: "3"

services:

  runtime-setup:
    image: netty-io_uring:centos-6-1.8
    build:
      args:
        java_version : "adopt@1.8.0-292"

  build-leak:
    image: netty-io_uring:centos-6-1.8

  build:
    image: netty-io_uring:centos-6-1.8

  deploy:
    image: netty-io_uring:centos-6-1.8

  stage-snapshot:
    image: netty-io_uring:centos-6-1.8

  stage-release:
    image: netty-io_uring:centos-6-1.8

  shell:
    image: netty-io_uring:centos-6-1.8
