version: "3"

services:

  runtime-setup:
    image: netty-io_uring:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos6

  common: &common
    image: netty-io_uring:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  build-leak:
    <<: *common
    command: /bin/bash -cl "mvn -Pleak clean test -Dio.netty.testsuite.badHost=netty.io"

  build: 
    <<: *common
    command: /bin/bash -cl "mvn clean package -Dio.netty.testsuite.badHost=netty.io"

  deploy:
    <<: *common
    command: /bin/bash -cl "mvn clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  stage-snapshot:
    <<: *common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "./mvnw clean package org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true"

  stage-release:
    <<: *common
    environment:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "./mvnw clean package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true -Dgpg.passphrase=$GPG_PASSPHRASE -Dgpg.keyname=$GPG_KEYNAME"


  shell:
    <<: *common
    environment:
      - SONATYPE_USER
      - SONATYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
      - ~/.m2:/root/.m2:delegated
    entrypoint: /bin/bash
